name: Config Server CI with Gradle & Jib

on:
  workflow_dispatch:

jobs:
  build:
    env:
      APP_NAME: config-service
      GIT_URI: ${{ github.server_url }}/${{ github.repository }}

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      # Set up JDK 20
      - name: Set up JDK 20
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '20'

      # Cache the Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('configuration-service/**/*.gradle*', 'configuration-service/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Grant execute permission for Gradle wrapper
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x configuration-service/gradlew

      # Build the project
      - name: Build with Gradle
        run: cd configuration-service && ./gradlew build

      # Create JAR file
      - name: Create JAR file
        run: cd configuration-service && ./gradlew bootJar

      # Upload the JAR artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: ${{ env.APP_NAME }}-jar
          path: configuration-service/build/libs/*.jar

      # Run tests
      - name: Run tests
        run: cd configuration-service && ./gradlew test

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push Docker image using Jib
      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          GIT_URI: ${{ env.GIT_URI }}
        run: cd configuration-service && ./gradlew jib
