name: Config Server CI with Gradle & Jib

on:
  workflow_dispatch:

jobs:
  build:
    env:
      APP_NAME: config-service
      GIT_URI: ${{ github.server_url }}/${{ github.repository }}

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      # Set up JDK 20
      - name: Set up JDK 20
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '20'

      # Cache the Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('configuration-service/**/*.gradle*', 'configuration-service/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Grant execute permission for Gradle wrapper
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x configuration-service/gradlew

      # Run tests
      - name: Run tests
        run: cd configuration-service && ./gradlew test

      # Build and push Docker image using Jib
      - name: Build and push Docker image
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
        run: cd catalog-service && ./gradlew jib